stages:
  data_ingestion:
    cmd: PYTHONPATH=. uv run python src/components/data/data_ingestion.py
    deps:
    - src/components/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: PYTHONPATH=. uv run python src/components/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/components/data/data_preprocessing.py
    - src/utils/common.py
    outs:
    - data/interim

  model_building:
    cmd: PYTHONPATH=. uv run python src/components/model/model_building.py
    deps:
    - data/interim/train_processed.csv
    - src/components/model/model_building.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - model/lgbm_model.pkl
    - model/tfidf_vectorizer.pkl

  model_evaluation:
    cmd: PYTHONPATH=. uv run python src/components/model/model_evaluation.py
    deps:
    - model/lgbm_model.pkl
    - model/tfidf_vectorizer.pkl
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - src/components/model/model_evaluation.py
    outs:
    - experiment_info.json

  model_registration:
    cmd: PYTHONPATH=. uv run python src/components/model/register_model.py
    deps:
    - experiment_info.json
    - src/components/model/register_model.py